<?php

namespace Database\Seeders;

use App\Models\Package;
use Illuminate\Database\Seeder;

class PackageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $packages = [
            [
                'name' => 'Laravel Filament',
                'slug' => 'laravel-filament',
                'description' => 'A collection of beautiful full-stack components for Laravel. The perfect starting point for your next app.',
                'status' => 'Released',
                'icon' => '🎨',
                'url' => 'https://filamentphp.com',
                'github_url' => 'https://github.com/filamentphp/filament',
                'packagist_url' => 'https://packagist.org/packages/filament/filament',
                'documentation_url' => 'https://filamentphp.com/docs',
                'version' => '3.2.0',
                'downloads_count' => 2500000,
                'stars_count' => 18500,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Laravel Livewire',
                'slug' => 'laravel-livewire',
                'description' => 'A magical frontend framework for Laravel. Build modern, reactive, dynamic interfaces using PHP.',
                'status' => 'Released',
                'icon' => '⚡',
                'url' => 'https://livewire.laravel.com',
                'github_url' => 'https://github.com/livewire/livewire',
                'packagist_url' => 'https://packagist.org/packages/livewire/livewire',
                'documentation_url' => 'https://livewire.laravel.com/docs',
                'version' => '3.4.9',
                'downloads_count' => 15000000,
                'stars_count' => 22000,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Laravel Sanctum',
                'slug' => 'laravel-sanctum',
                'description' => 'Laravel Sanctum provides a featherweight authentication system for SPAs and simple APIs.',
                'status' => 'Released',
                'icon' => '🔐',
                'url' => 'https://laravel.com/docs/sanctum',
                'github_url' => 'https://github.com/laravel/sanctum',
                'packagist_url' => 'https://packagist.org/packages/laravel/sanctum',
                'documentation_url' => 'https://laravel.com/docs/sanctum',
                'version' => '4.0.2',
                'downloads_count' => 45000000,
                'stars_count' => 2700,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Laravel Fortify',
                'slug' => 'laravel-fortify',
                'description' => 'Laravel Fortify is a frontend agnostic authentication backend for Laravel.',
                'status' => 'Released',
                'icon' => '🛡️',
                'url' => 'https://laravel.com/docs/fortify',
                'github_url' => 'https://github.com/laravel/fortify',
                'packagist_url' => 'https://packagist.org/packages/laravel/fortify',
                'documentation_url' => 'https://laravel.com/docs/fortify',
                'version' => '1.21.1',
                'downloads_count' => 8500000,
                'stars_count' => 1800,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Laravel Horizon',
                'slug' => 'laravel-horizon',
                'description' => 'Dashboard and code-driven configuration for Laravel\'s Redis queues.',
                'status' => 'Released',
                'icon' => '📊',
                'url' => 'https://laravel.com/docs/horizon',
                'github_url' => 'https://github.com/laravel/horizon',
                'packagist_url' => 'https://packagist.org/packages/laravel/horizon',
                'documentation_url' => 'https://laravel.com/docs/horizon',
                'version' => '5.24.5',
                'downloads_count' => 12000000,
                'stars_count' => 3900,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Laravel Telescope',
                'slug' => 'laravel-telescope',
                'description' => 'An elegant debug assistant for the Laravel framework.',
                'status' => 'Released',
                'icon' => '🔭',
                'url' => 'https://laravel.com/docs/telescope',
                'github_url' => 'https://github.com/laravel/telescope',
                'packagist_url' => 'https://packagist.org/packages/laravel/telescope',
                'documentation_url' => 'https://laravel.com/docs/telescope',
                'version' => '5.0.4',
                'downloads_count' => 18000000,
                'stars_count' => 4800,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Pest PHP',
                'slug' => 'pest-php',
                'description' => 'Pest is a testing framework with a focus on simplicity. It was carefully crafted to bring back the joy of testing in PHP.',
                'status' => 'Released',
                'icon' => '🧪',
                'url' => 'https://pestphp.com',
                'github_url' => 'https://github.com/pestphp/pest',
                'packagist_url' => 'https://packagist.org/packages/pestphp/pest',
                'documentation_url' => 'https://pestphp.com/docs',
                'version' => '2.34.7',
                'downloads_count' => 25000000,
                'stars_count' => 9200,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => 'Laravel Pint',
                'slug' => 'laravel-pint',
                'description' => 'Laravel Pint is an opinionated PHP code style fixer for minimalists.',
                'status' => 'Released',
                'icon' => '✨',
                'url' => 'https://laravel.com/docs/pint',
                'github_url' => 'https://github.com/laravel/pint',
                'packagist_url' => 'https://packagist.org/packages/laravel/pint',
                'documentation_url' => 'https://laravel.com/docs/pint',
                'version' => '1.15.2',
                'downloads_count' => 35000000,
                'stars_count' => 2800,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Laravel Octane',
                'slug' => 'laravel-octane',
                'description' => 'Supercharge your Laravel application\'s performance by serving it via high-powered application servers.',
                'status' => 'Released',
                'icon' => '🚀',
                'url' => 'https://laravel.com/docs/octane',
                'github_url' => 'https://github.com/laravel/octane',
                'packagist_url' => 'https://packagist.org/packages/laravel/octane',
                'documentation_url' => 'https://laravel.com/docs/octane',
                'version' => '2.4.0',
                'downloads_count' => 5500000,
                'stars_count' => 3700,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Laravel Pulse',
                'slug' => 'laravel-pulse',
                'description' => 'Laravel Pulse delivers at-a-glance insights into your application\'s performance and usage.',
                'status' => 'Released',
                'icon' => '💓',
                'url' => 'https://laravel.com/docs/pulse',
                'github_url' => 'https://github.com/laravel/pulse',
                'packagist_url' => 'https://packagist.org/packages/laravel/pulse',
                'documentation_url' => 'https://laravel.com/docs/pulse',
                'version' => '1.2.4',
                'downloads_count' => 2800000,
                'stars_count' => 1300,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'name' => 'Laravel Prompts',
                'slug' => 'laravel-prompts',
                'description' => 'Beautiful and user-friendly forms for your command-line PHP applications.',
                'status' => 'Released',
                'icon' => '📝',
                'url' => 'https://laravel.com/docs/prompts',
                'github_url' => 'https://github.com/laravel/prompts',
                'packagist_url' => 'https://packagist.org/packages/laravel/prompts',
                'documentation_url' => 'https://laravel.com/docs/prompts',
                'version' => '0.1.17',
                'downloads_count' => 8000000,
                'stars_count' => 2400,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'Laravel Folio',
                'slug' => 'laravel-folio',
                'description' => 'Laravel Folio is a powerful page based router designed to simplify routing in Laravel applications.',
                'status' => 'Released',
                'icon' => '📄',
                'url' => 'https://laravel.com/docs/folio',
                'github_url' => 'https://github.com/laravel/folio',
                'packagist_url' => 'https://packagist.org/packages/laravel/folio',
                'documentation_url' => 'https://laravel.com/docs/folio',
                'version' => '1.1.12',
                'downloads_count' => 1200000,
                'stars_count' => 1100,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'name' => 'Spatie Permission',
                'slug' => 'spatie-permission',
                'description' => 'Associate users with permissions and roles in Laravel.',
                'status' => 'Released',
                'icon' => '👑',
                'url' => 'https://spatie.be/docs/laravel-permission',
                'github_url' => 'https://github.com/spatie/laravel-permission',
                'packagist_url' => 'https://packagist.org/packages/spatie/laravel-permission',
                'documentation_url' => 'https://spatie.be/docs/laravel-permission',
                'version' => '6.7.0',
                'downloads_count' => 42000000,
                'stars_count' => 11800,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'name' => 'Spatie Query Builder',
                'slug' => 'spatie-query-builder',
                'description' => 'Easily build Eloquent queries from API requests.',
                'status' => 'Released',
                'icon' => '🔍',
                'url' => 'https://spatie.be/docs/laravel-query-builder',
                'github_url' => 'https://github.com/spatie/laravel-query-builder',
                'packagist_url' => 'https://packagist.org/packages/spatie/laravel-query-builder',
                'documentation_url' => 'https://spatie.be/docs/laravel-query-builder',
                'version' => '5.8.0',
                'downloads_count' => 15000000,
                'stars_count' => 4000,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'name' => 'Laravel Excel',
                'slug' => 'laravel-excel',
                'description' => 'Supercharged Excel exports and imports in Laravel.',
                'status' => 'Released',
                'icon' => '📊',
                'url' => 'https://laravel-excel.com',
                'github_url' => 'https://github.com/SpartnerNL/Laravel-Excel',
                'packagist_url' => 'https://packagist.org/packages/maatwebsite/excel',
                'documentation_url' => 'https://laravel-excel.com/docs',
                'version' => '3.1.48',
                'downloads_count' => 55000000,
                'stars_count' => 12000,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 15,
            ],
            [
                'name' => 'Laravel Breeze',
                'slug' => 'laravel-breeze',
                'description' => 'Laravel Breeze is a minimal, simple implementation of all of Laravel\'s authentication features.',
                'status' => 'Released',
                'icon' => '🌬️',
                'url' => 'https://laravel.com/docs/starter-kits#laravel-breeze',
                'github_url' => 'https://github.com/laravel/breeze',
                'packagist_url' => 'https://packagist.org/packages/laravel/breeze',
                'documentation_url' => 'https://laravel.com/docs/starter-kits#laravel-breeze',
                'version' => '2.0.2',
                'downloads_count' => 8500000,
                'stars_count' => 2700,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 16,
            ],
            [
                'name' => 'Laravel Jetstream',
                'slug' => 'laravel-jetstream',
                'description' => 'Laravel Jetstream is a beautifully designed application scaffolding for Laravel.',
                'status' => 'Released',
                'icon' => '✈️',
                'url' => 'https://jetstream.laravel.com',
                'github_url' => 'https://github.com/laravel/jetstream',
                'packagist_url' => 'https://packagist.org/packages/laravel/jetstream',
                'documentation_url' => 'https://jetstream.laravel.com',
                'version' => '5.1.2',
                'downloads_count' => 5200000,
                'stars_count' => 3900,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 17,
            ],
            [
                'name' => 'Laravel Cashier',
                'slug' => 'laravel-cashier',
                'description' => 'Laravel Cashier provides an expressive, fluent interface to Stripe\'s subscription billing services.',
                'status' => 'Released',
                'icon' => '💰',
                'url' => 'https://laravel.com/docs/billing',
                'github_url' => 'https://github.com/laravel/cashier-stripe',
                'packagist_url' => 'https://packagist.org/packages/laravel/cashier',
                'documentation_url' => 'https://laravel.com/docs/billing',
                'version' => '15.3.2',
                'downloads_count' => 12000000,
                'stars_count' => 2300,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 18,
            ]
        ];

        foreach ($packages as $packageData) {
            Package::query()->firstOrCreate(
                ['slug' => $packageData['slug']],
                $packageData
            );
        }
    }
}
